accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('accounts/', views.users_list, name='users'),
    path('accounts/new/', views.user_new, name='user_new'),
    path('accounts/<int:pk>/deactivate/', views.user_change_is_active, name='user_change_is_active'),
    path('password/', views.change_password, name='change_password'),
    path('accounts/<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('accounts/<int:pk>/reset-password/', views.user_reset_password, name='user_reset_password'),
    
]

jud_in_foco/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView
import teenagers

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teenagers.urls')),
    path('', include('accounts.urls')),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('django.contrib.auth.urls'), name='login'),
    path('', RedirectView.as_view(pattern_name='login', permanent=False),),
]

teenagers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('teenagers/', views.teenagers_list, name='teenagers'),
    path('teenagers/new/', views.teenager_new, name='teenager_new'),
    path('teenagers/<int:pk>/change_status/', views.teenager_change_status, name='teenager_change_status'),
    path('teenagers/<int:pk>/edit/', views.teenager_edit, name='teenager_edit'),
]

teenagers/models.py
from django.db import models

# Create your models here.
class Teenager(models.Model):
    
    name = models.CharField(
        verbose_name = 'Nome',
        max_length = 255,
        null = False ,
        blank = False
    )

    name_mother = models.CharField(
        verbose_name = 'Nome da mãe',
        max_length = 255,
        null = False,
        blank = False
    )

    name_father = models.CharField(
        verbose_name = 'Nome do pai',
        max_length = 255,
        null = True,
        blank = True
    )

    date_birth = models.DateField(
        verbose_name = 'Data de Nascimento',
        null = False,
        blank = False,
        auto_now= False
    )

    type_sex = models.CharField(
        verbose_name = 'Sexo',
        max_length = 20,
        null = True,
        blank = True
    )

    notes = models.CharField(
        verbose_name = 'Observações',
        max_length = 20,
        null = True,
        blank = True
    )

    address = models.CharField(
        verbose_name = 'Endereço',
        max_length = 355,
        null = True,
        blank = True
    )
    
    is_active = models.BooleanField(
        verbose_name = 'Ativo?',
        default= True
    )

    objects = models.Manager()

teenagers/forms.py
from django import forms
from .models import Teenager

class TeenagerForm(forms.ModelForm):

    class Meta:
        model = Teenager
        fields = (
                'name',       
                'name_mother',
                'name_father',
                'date_birth',
                'type_sex',
                'address',
                'notes'
                )

class TeenagerChangeForm(forms.ModelForm):
    
    class Meta:
        model = Teenager
        fields = [
                'name',       
                'name_mother',
                'name_father',
                'date_birth',
                'type_sex',
                'address',
                'notes'
        ]

teenagers/views.py
import logging
from .forms import TeenagerForm
from .models import Teenager
from django.shortcuts import render
from django.contrib import messages
# Create your views here.

logger = logging.getLogger('django')


def teenagers_list(request):
    teenagers = Teenager.objects.all()
    return render(request, 'teenagers/teenagers.html', {'teenagers': teenagers})

def teenager_new(request):
    if request.method == "POST":
        teenager = TeenagerForm(request.POST)
        if teenager.is_valid():
            teenager.save()
            messages.success(request, 'Adolescente cadastrado com sucesso.')
        else:
            messages.warning(request, 'Falha no cadastro')
    form = TeenagerForm()
    return render(request, 'teenagers/teenager_new.html', {'form': form})


def teenager_edit(request, pk):
    try:
        teenager = Teenager.objects.get(pk=pk)
        form = TeenagerForm(request.POST, instance=teenager) or None
        logger.info(str(request.POST))
        if request.method == 'POST':
            if form.is_valid():
                teenager = form.save()
                messages.success(request, 'Dados do(a) adolescente alterado`s com sucesso.')
            else:
                messages.warning(request, 'Falha na alteração. Formulário Inválido.')
    except Exception as e:
            messages.warning(request, 'Falha na alteração. Detalhe: +' + str(e))
    return render(request, 'teenagers/teenager_edit.html', {'form': form, 'teenager': teenager})
    

def teenager_change_status(request, pk):
    try:
        if request.method == "POST":
            teenager = Teenager.objects.get(pk=pk)
            if teenager.is_active:
                teenager.is_active = False
            else:
                teenager.is_active = True
            teenager.save()
            messages.success(request, 'Situação do(a) adolescente alterada com sucesso.')
    except Exception as e:
        messages.warning(request, 'Falha. Detalhe: +' + str(e))
    teenagers = Teenager.objects.all()
    return render(request, 'teenagers/teenagers.html', {'teenagers': teenagers})
    

teenagers/templates/teenagers/teenager_edit.html
<!-- templates/users.html-->
{% extends 'base.html' %}

{% block content %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Editar Adolescente</h1>

</div>
<p class="mb-4">Ambiente de gestão dos(as) adolescentes da plataforma Jud <i>in</i> Foco.</p>
<!-- end Page Heading -->



<!-- Messages -->
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{ message.tags }}" role="alert" {% endif %}>
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
<!-- end messages -->

<div class="card mb-4">
  <div class="card-header">
    Dados do Adolescente
  </div>
  <div class="card-body">
    <!-- Inicio do formulário -->

    <form class="teenagers" method="POST">
      {% csrf_token %}



      <div class="form-group">
        <input type="text" class="form-control " name="name" required id="id_name" placeholder="Nome do adolescente" value="{{ teenager.name }}">
      </div>

      <div class="form-group">
        <input type="text" class="form-control " name="name_mother" required id="id_name_mother"
          placeholder="Nome do mãe" value="{{ teenager.name_mother }}">
      </div>

      <div class="form-group">
        <input type="text" class="form-control " name="name_father" required id="id_name_father"
          placeholder="Nome do pai" value="{{ teenager.name_father|default:"" }}">
      </div>

      <div class="form-group row">
        <div class="col-sm-2 mb-3 mb-sm-0">
          <input placeholder="Data de Nascimento" class="form-control" type="text" onfocus="(this.type='date')"
            name="date_birth" id="id_date_birth" value="{{ teenager.date_birth|date:"d/m/Y" }}">
        </div>

        <div class="col-sm-2">
          <select class="form-control" name="type_sex" id="id_type_sex">
            <option {% if teenager.type_sex == None %} selected >{% else %}>{% endif %}Sexo</option>
            <option value="1" {% if teenager.type_sex == '1' %} selected > {% else %} >{% endif %} Masculino</option>
            <option value="2" {% if teenager.type_sex == '2' %} selected > {% else %} >{% endif %} Feminino</option>
            <option value="3" {% if teenager.type_sex == '3' %} selected > {% else %} > {% endif %} Outros</option>
          </select>
        </div>

      <div class="form-group col-sm-8">
        <input type="text" class="form-control " name="address" required id="id_address" placeholder="Endereço Completo" value="{{ teenager.address|default:"" }}">
      </div>

      </div>

      <div class="form-group">
        <textarea rows="3"  class="form-control " name="notes" required id="id_notes" placeholder="Observacao">{{ teenager.notes|default:"" }}</textarea>
      </div>

      <hr>
      <!-- buttons -->
      <div class="form-group row">
        <div class="col-sm">
          <a href="{% url 'teenagers' %}" class="btn btn-secondary btn-user btn-block">
            Voltar
          </a>
        </div>
        <div class="col-sm">
          <button type="reset" class="btn btn-danger btn-user btn-block">
            Limpar
          </button>
        </div>
        <div class="col-sm">
          <button type="submit" class="btn btn-primary btn-user btn-block">
            Editar Adolescente
          </button>
        </div>
      </div>
      <!-- End buttons -->
    </form>

  </div>
</div>

</div>

{% endblock %}

teenagers/templates/teenagers/teenager_new.html
<!-- templates/users.html-->
{% extends 'base.html' %}

{% block content %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Novo(a) Adolescente</h1>

</div>
<p class="mb-4">Ambiente de gestão dos(as) adolescentes da plataforma Jud <i>in</i> Foco.</p>
<!-- end Page Heading -->



<!-- Messages -->
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{ message.tags }}" role="alert" {% endif %}>
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
<!-- end messages -->

<div class="card mb-4">
  <div class="card-header">
    Dados do Adolescente
  </div>
  <div class="card-body">
    <!-- Inicio do formulário -->

    <form class="teenagers" method="POST">
      {% csrf_token %}



      <div class="form-group">
        <input type="text" class="form-control " name="name" required id="id_name" placeholder="Nome do adolescente">
      </div>

      <div class="form-group">
        <input type="text" class="form-control " name="name_mother" required id="id_name_mother"
          placeholder="Nome do mãe">
      </div>

      <div class="form-group">
        <input type="text" class="form-control " name="name_father" id="id_name_father"
          placeholder="Nome do pai">
      </div>

      <div class="form-group row">
        <div class="col-sm-2 mb-3 mb-sm-0">
          <input placeholder="Data de Nascimento" class="form-control" type="text" required onfocus="(this.type='date')"
            name="date_birth" id="id_date_birth">
        </div>

        <div class="col-sm-2">
          <select class="form-control" name="type_sex" id="id_type_sex">
            <option selected>Sexo</option>
            <option value="1">Masculino</option>
            <option value="2">Feminino</option>
            <option value="3">Outros</option>
          </select>
        </div>

      <div class="form-group col-sm-8">
        <input type="text" class="form-control " name="address" id="id_address" placeholder="Endereço Completo">
      </div>

      </div>

      <div class="form-group">
        <textarea rows="3"  class="form-control " name="notes"  id="id_notes" placeholder="Observacao"></textarea>
      </div>

      <hr>
      <!-- buttons -->
      <div class="form-group row">
        <div class="col-sm">
          <a href="{% url 'teenagers' %}" class="btn btn-secondary btn-user btn-block">
            Voltar
          </a>
        </div>
        <div class="col-sm">
          <button type="reset" class="btn btn-danger btn-user btn-block">
            Limpar
          </button>
        </div>
        <div class="col-sm">
          <button type="submit" class="btn btn-primary btn-user btn-block">
            Cadastrar Adolescente
          </button>
        </div>
      </div>
      <!-- End buttons -->
    </form>

  </div>
</div>

</div>

{% endblock %}

teenagers/templates/teenagers/teenagers.html
<!-- templates/users.html-->
{% extends 'base.html' %}

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Adolescentes</h1>

  <a href="{% url 'teenager_new' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
      class="fas fa-plus-circle fa-sm text-white-50"></i> Novo(a) Adolescente</a>
</div>
<p class="mb-4">Ambiente de gestão dos adolescentes da plataforma Jud <i>in</i> Foco.</p>


<!-- Messages -->
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{ message.tags }}" role="alert" {% endif %}>
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
<!-- end messages -->


<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Lista de Adolescentes</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Nome do(a) Adolescente</th>
            <th>Nome da Mãe</th>
            <th>Data de Nascimento</th>
            <th>Sexo</th>
            <th>Situação</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          {% for teenager in teenagers %}
          <tr>
            <td>{{ teenager.name }}</td>
            <td>{{ teenager.name_mother }}</td>
            <td>{{ teenager.date_birth}}</td>
            <td>{% if teenager.type_sex == '1' %}
                    Masculino
                {% elif teenager.type_sex == '2' %}
                    Feminino
                {% elif teenager.type_sex == '3' %}
                    Outros
                {% else %}
                    Não informado
                {% endif %}
            </td>
            <td>{% if teenager.is_active == True %}
                    Ativo
                {% else %}
                    Inativo
                {% endif %}
            </td>
            <td>
              <center>
                <div class="dropdown no-arrow btn-sm btn-info btn-circle">
                  <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bars text-gray-100"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                    aria-labelledby="dropdownMenuLink" x-placement="bottom-end"
                    style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-156px, 19px, 0px);">
                    <div class="dropdown-header">Ações:</div>
                    <a class="dropdown-item" href="{% url 'teenager_edit' pk=teenager.pk %}">Editar</a>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#ConfirmationModal"
                      onclick="setActionConfirmationModal('{% url 'teenager_change_status' pk=teenager.pk %}', 'Ao confirmar você mudará a situação do adolescente.' )">
                      {% if teenager.is_active == True %}
                      Inativar
                      {% else %}
                      Ativar
                      {% endif %}
                    </a>
          
                  </div>
                </div>
              </center>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>


<script>
  function setActionConfirmationModal(url, msg) {
    document.getElementById("formConfirmationModal").action = url;
    document.getElementById("textModal").innerHTML = msg;
  }
</script>


<div class="modal fade" id="ConfirmationModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form id="formConfirmationModal" method='post' class="form" role="form" action="#">
        {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="ModalLabel">Você tem certeza disso?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body" id="textModal"></div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
          <button class="btn btn-primary" type="submit">Confirmar</button>
        </div>
      </form>
    </div>
  </div>






</div>




{% endblock %}